inherit_from: .rubocop_todo.yml

AllCops:
  StyleGuideCopsOnly: true

# Uncomment when the repository is ready
# Metrics/LineLength:
#   Max: 100

Metrics/MethodLength:
  Enabled: false

Style/Alias:
  Enabled: false

Style/SignalException:
  Enabled: false

# Uncomment when the repository is ready
# Style/StringLiterals:
#   EnforcedStyle: single_quotes

Style/TrivialAccessors:
  ExactNameMatch: true
